services:
  - type: web
    name: user-management-backend
    env: node
    rootDir: user-management-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
