[build]
  base = "user-management-frontend"
  publish = "user-management-frontend/dist/user-management-frontend"
  command = "npm install && ng build user-management-frontend --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
