services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/user-management-frontend
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 