services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/user-management-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 